import { RemotePeer } from ".";

export const CREATE_NEW_P2P_CONNECTION = 'CREATE_NEW_P2P_CONNECTION';
export const MAKE_P2P_OFFER = 'MAKE_P2P_OFFER';
export const DELIVER_ANSWER = 'SOCKET_DELIVER_ANSWER';
export const ON_TRACK_ADDED_TO_PEER_CONNECTION = 'ON_TRACK_ADDED_TO_PEER_CONNECTION';
export const RENEGOTIATE_CONNECTION = 'RENEGOTIATE_CONNECTION';
export const DELIVER_OFFER = 'SOCKET_DELIVER_OFFER';