export const ADD_P2P_CONNECTION = 'ADD_P2P_CONNECTION';
export const SET_P2P_RECIEVED = 'SET_P2P_RECIEVED';
export const UPDATE_USER_LIST = 'SOCKET_UPDATE_USER_LIST';
export const SET_REMOTE_MEDIA_STREAM = 'SET_REMOTE_MEDIA_STREAM';
export const UPDATE_OFFER = 'UPDATE_OFFER';
export const UPDATE_P2P_CONN = 'UPDATE_P2P_CONN';
export const ADD_TRACK_TO_P2P_CONNECTION = 'ADD_TRACK_TO_P2P_CONNECTION';
