export const ADD_P2P_CONNECTION = 'ADD_P2P_CONNECTION';
export const SET_P2P_RECIEVED = 'SET_P2P_RECIEVED';
export const UPDATE_USER_LIST = 'SOCKET_UPDATE_USER_LIST';
export const SET_REMOTE_MEDIA_STREAM = 'SET_REMOTE_MEDIA_STREAM';
