export const MEDIA_STREAM_OFFER = 'SOCKET_MEDIA_STREAM_OFFER';
export const MEDIA_STREAM_ACCEPTED = 'SOCKET_MEDIA_STREAM_ACCEPTED';
export const ON_TRACK_ADDED_TO_PEER_CONNECTION = 'ON_TRACK_ADDED_TO_PEER_CONNECTION';
